# Generated by Django 2.2.19 on 2022-08-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220812_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measure_unit',
            field=models.CharField(max_length=15, verbose_name='Единицы измерения'),
        ),
    ]
