# Generated by Django 3.2.15 on 2022-08-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20220818_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientforrecipe',
            old_name='quantity',
            new_name='amount',
        ),
    ]
