# Generated by Django 3.2.15 on 2022-08-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename_tag_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=models.CharField(choices=[('#0000FF', 'Синий'), ('#008000', 'Зеленый'), ('#800080', 'Фиолетовый')], max_length=10, unique=True, verbose_name='Цвет'),
        ),
    ]
