# Generated by Django 3.2.5 on 2022-08-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20220825_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='colour',
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default=1, max_length=10, verbose_name='Цвет в Hex'),
            preserve_default=False,
        ),
    ]
