# Generated by Django 3.2.5 on 2022-08-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20220825_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=models.CharField(max_length=10, verbose_name='Цвет в Hex'),
        ),
    ]
